---
- name: debian | Installing bridge-utils
  apt:
    name: ["bridge-utils"]
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Installing Bonding Packages
  apt:
    name: ["ifenslave"]
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Installing VLAN Packages
  apt:
    name: ["vlan"]
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Configuring Defined Interfaces
  template:
    src: "{{ config_interface_template }}"
    dest: "{{ config_interfaces_path }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  register: config_interface
  become: true
